apiVersion: v1
kind: Service
metadata:
  name: postgis
spec:
  ports:
    - port: 5432
  selector:
    app: postgis
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgis-initdb-config
data:
  initdb.sql: |
    /* nothing to see here */
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
spec:
  selector:
    matchLabels:
      app: postgis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
        - image: postgis/postgis:12-3.0
          name: postgis
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis-root-password
                  key: password
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: mysql
          volumeMounts:
            - name: postgisdb
              mountPath: /var/lib/postgresql/data
            - name: postgis-initdb
              mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              cpu: "400m"
              memory: 200Mi
            requests:
              cpu: "50m"
              memory: 150Mi
      volumes:
        - name: postgisdb
          persistentVolumeClaim:
            claimName: postgis-pv-claim
        - name: postgis-initdb
          configMap:
            name: postgis-initdb-config
