apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgis-persistentvolume
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: postgis-pv-claim
  gcePersistentDisk:
    fsType: ext4
    readOnly: false
    pdName: gke-november3-2c2d634a-pvc-a501839c-642e-466f-a14d-ebb0ee174daf
  persistentVolumeReclaimPolicy: Retain