apiVersion: v1
kind: Service
metadata:
  name: postgis
spec:
  ports:
    - port: 5432
  selector:
    app: postgis
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
spec:
  selector:
    matchLabels:
      app: postgis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
        - image: postgis/postgis:12-3.0
          name: postgis
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis-root-password
                  key: password
            - name: POSTGRES_DB
              value: postsdb
            - name: POSTGRES_USER
              value: postgres
          ports:
            - containerPort: 5432
              name: mysql
          volumeMounts:
            - name: postgisdb
              mountPath: /var/lib/postgresql
          resources:
            limits:
              cpu: "100m"
              memory: 512Mi
            requests:
              cpu: "20m"
              memory: 256Mi
      volumes:
        - name: postgisdb
          persistentVolumeClaim:
            claimName: postgis-pv-claim