apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgis-persistentvolume
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: postgis-pv-claim
  gcePersistentDisk:
    fsType: ext4
    readOnly: false
    pdName:
  persistentVolumeReclaimPolicy: Retain