apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-pv-claim
  labels:
    app: reactivepostsdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi