apiVersion: v1
kind: ConfigMap
metadata:
  name: reactiveposts
data:
  spring.jpa.hibernate.ddl-auto: validate
  spring.datasource.url: jdbc:postgresql://postgis:5432/postsdb
  spring.datasource.username: postgres
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
  spring.datasource.driver-class-name: org.postgresql.Driver
  reactiveposts.threads-update-interval: "30m"
  reactiveposts.threads-update-max-retries: "2"
  reactiveposts.index-depth: "2"
  reactiveposts.posts-update-interval: "69s"
  reactiveposts.posts-update-max-retries: "2"