apiVersion: v1
kind: Service
metadata:
  name: reactiveposts
spec:
  ports:
    - port: 8080
  selector:
    app: reactiveposts
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactiveposts
spec:
  selector:
    matchLabels:
      app: reactiveposts
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reactiveposts
    spec:
      containers:
        - image: gcr.io/badinko/reactiveposts:0.3.0
          name: reactiveposts
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis-root-password
                  key: password
            - name: JAVA_OPTS
              value: >-
                    -XX:MaxMetaspaceSize=100M
                    -XX:ReservedCodeCacheSize=100M
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: "1500m"
              memory: "380Mi"
            requests:
              cpu: "50m"
              memory: "250Mi"
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 30
            successThreshold: 1
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            successThreshold: 1
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
      serviceAccountName: reactiveposts

